# MCP Server Configuration
server:
  host: "0.0.0.0"
  port: 8080
  debug: true

# Proxy Configuration
proxies:
  - name: "proxy1"
    host: "proxy.example.com"
    port: 8080
    username: "${PROXY_USERNAME}"
    password: "${PROXY_PASSWORD}"

# Scraping Configuration
scraping:
  max_concurrent_requests: 5
  request_timeout: 30
  retry_attempts: 3
  user_agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36"
  rate_limit:
    requests_per_minute: 60
    burst_size: 10

# Data Storage
storage:
  type: "local"  # local, s3, gcs
  path: "data"
  backup_enabled: true
  backup_interval: "1h"

# Logging
logging:
  level: "INFO"
  file: "mcp.log"
  max_size: "100MB"
  max_backups: 5 